// <auto-generated />
using System;
using Cwiczenie7.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cwiczenie7.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cwiczenie7.Models.Component", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)");

                    b.Property<int>("ComponentManufacturersId")
                        .HasColumnType("int");

                    b.Property<int>("ComponentTypesId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Code");

                    b.HasIndex("ComponentManufacturersId");

                    b.HasIndex("ComponentTypesId");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Code = "INT-I9-14X",
                            ComponentManufacturersId = 1,
                            ComponentTypesId = 1,
                            Description = "High end gaming CPU",
                            Name = "Intel Core i9-14900K"
                        },
                        new
                        {
                            Code = "AMD-R9-79X",
                            ComponentManufacturersId = 2,
                            ComponentTypesId = 1,
                            Description = "Top tier AMD CPU",
                            Name = "AMD Ryzen 9 7950X3D"
                        },
                        new
                        {
                            Code = "NVD-RTX40X",
                            ComponentManufacturersId = 3,
                            ComponentTypesId = 2,
                            Description = "Best consumer GPU",
                            Name = "NVIDIA GeForce RTX 4090"
                        });
                });

            modelBuilder.Entity("Cwiczenie7.Models.ComponentManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FoundationDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "INTEL",
                            FoundationDate = new DateTime(1968, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Intel Corporation"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "AMD",
                            FoundationDate = new DateTime(1969, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Advanced Micro Devices"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "NVIDIA",
                            FoundationDate = new DateTime(1993, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "NVIDIA Corporation"
                        });
                });

            modelBuilder.Entity("Cwiczenie7.Models.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CPU",
                            Name = "Central Processing Unit"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "GPU",
                            Name = "Graphics Processing Unit"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "RAM",
                            Name = "Random Access Memory"
                        });
                });

            modelBuilder.Entity("Cwiczenie7.Models.PC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("PCs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gaming Beast X",
                            Stock = 5,
                            Warranty = 36,
                            Weight = 12.5
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 15, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            Name = "Office Mini Pro",
                            Stock = 12,
                            Warranty = 24,
                            Weight = 4.2000000000000002
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Home Station",
                            Stock = 8,
                            Warranty = 24,
                            Weight = 8.0
                        });
                });

            modelBuilder.Entity("Cwiczenie7.Models.PCComponent", b =>
                {
                    b.Property<int>("PCId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentCode")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("PCId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("PCComponents");

                    b.HasData(
                        new
                        {
                            PCId = 1,
                            ComponentCode = "INT-I9-14X",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 1,
                            ComponentCode = "NVD-RTX40X",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 2,
                            ComponentCode = "AMD-R9-79X",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "NVD-RTX40X",
                            Amount = 1
                        });
                });

            modelBuilder.Entity("Cwiczenie7.Models.Component", b =>
                {
                    b.HasOne("Cwiczenie7.Models.ComponentManufacturer", "ComponentManufacturer")
                        .WithMany("Components")
                        .HasForeignKey("ComponentManufacturersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cwiczenie7.Models.ComponentType", "ComponentType")
                        .WithMany("Components")
                        .HasForeignKey("ComponentTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentManufacturer");

                    b.Navigation("ComponentType");
                });

            modelBuilder.Entity("Cwiczenie7.Models.PCComponent", b =>
                {
                    b.HasOne("Cwiczenie7.Models.Component", "Component")
                        .WithMany("PCComponents")
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cwiczenie7.Models.PC", "PC")
                        .WithMany("PCComponents")
                        .HasForeignKey("PCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("PC");
                });

            modelBuilder.Entity("Cwiczenie7.Models.Component", b =>
                {
                    b.Navigation("PCComponents");
                });

            modelBuilder.Entity("Cwiczenie7.Models.ComponentManufacturer", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("Cwiczenie7.Models.ComponentType", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("Cwiczenie7.Models.PC", b =>
                {
                    b.Navigation("PCComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
